/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProducaoRouteImport } from './routes/_authenticated/producao'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated/importar'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedStockIndexRouteImport } from './routes/_authenticated/stock.index'
import { Route as AuthenticatedEncomendasIndexRouteImport } from './routes/_authenticated/encomendas.index'
import { Route as AuthenticatedStockTecidosRouteImport } from './routes/_authenticated/stock.tecidos'
import { Route as AuthenticatedStockProducaoRouteImport } from './routes/_authenticated/stock.producao'
import { Route as AuthenticatedStockCascosRouteImport } from './routes/_authenticated/stock.cascos'
import { Route as AuthenticatedStockCapasRouteImport } from './routes/_authenticated/stock.capas'
import { Route as AuthenticatedProdutosReceitasRouteImport } from './routes/_authenticated/produtos.receitas'
import { Route as AuthenticatedProducaoCascosRouteImport } from './routes/_authenticated/producao.cascos'
import { Route as AuthenticatedEtiquetasImprimirRouteImport } from './routes/_authenticated/etiquetas.imprimir'
import { Route as AuthenticatedEncomendasNovaRouteImport } from './routes/_authenticated/encomendas.nova'
import { Route as AuthenticatedAdminColisRouteImport } from './routes/_authenticated/admin.colis'
import { Route as AuthenticatedAdminCatalogoRouteImport } from './routes/_authenticated/admin.catalogo'
import { Route as AuthenticatedEncomendasIdEtiquetaRouteImport } from './routes/_authenticated/encomendas.$id.etiqueta'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProducaoRoute = AuthenticatedProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockIndexRoute = AuthenticatedStockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEncomendasIndexRoute =
  AuthenticatedEncomendasIndexRouteImport.update({
    id: '/encomendas/',
    path: '/encomendas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockTecidosRoute =
  AuthenticatedStockTecidosRouteImport.update({
    id: '/stock/tecidos',
    path: '/stock/tecidos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockProducaoRoute =
  AuthenticatedStockProducaoRouteImport.update({
    id: '/stock/producao',
    path: '/stock/producao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockCascosRoute =
  AuthenticatedStockCascosRouteImport.update({
    id: '/stock/cascos',
    path: '/stock/cascos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockCapasRoute = AuthenticatedStockCapasRouteImport.update({
  id: '/stock/capas',
  path: '/stock/capas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosReceitasRoute =
  AuthenticatedProdutosReceitasRouteImport.update({
    id: '/produtos/receitas',
    path: '/produtos/receitas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProducaoCascosRoute =
  AuthenticatedProducaoCascosRouteImport.update({
    id: '/cascos',
    path: '/cascos',
    getParentRoute: () => AuthenticatedProducaoRoute,
  } as any)
const AuthenticatedEtiquetasImprimirRoute =
  AuthenticatedEtiquetasImprimirRouteImport.update({
    id: '/etiquetas/imprimir',
    path: '/etiquetas/imprimir',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEncomendasNovaRoute =
  AuthenticatedEncomendasNovaRouteImport.update({
    id: '/encomendas/nova',
    path: '/encomendas/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminColisRoute = AuthenticatedAdminColisRouteImport.update({
  id: '/admin/colis',
  path: '/admin/colis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCatalogoRoute =
  AuthenticatedAdminCatalogoRouteImport.update({
    id: '/admin/catalogo',
    path: '/admin/catalogo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEncomendasIdEtiquetaRoute =
  AuthenticatedEncomendasIdEtiquetaRouteImport.update({
    id: '/encomendas/$id/etiqueta',
    path: '/encomendas/$id/etiqueta',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/producao': typeof AuthenticatedProducaoRouteWithChildren
  '/admin/catalogo': typeof AuthenticatedAdminCatalogoRoute
  '/admin/colis': typeof AuthenticatedAdminColisRoute
  '/encomendas/nova': typeof AuthenticatedEncomendasNovaRoute
  '/etiquetas/imprimir': typeof AuthenticatedEtiquetasImprimirRoute
  '/producao/cascos': typeof AuthenticatedProducaoCascosRoute
  '/produtos/receitas': typeof AuthenticatedProdutosReceitasRoute
  '/stock/capas': typeof AuthenticatedStockCapasRoute
  '/stock/cascos': typeof AuthenticatedStockCascosRoute
  '/stock/producao': typeof AuthenticatedStockProducaoRoute
  '/stock/tecidos': typeof AuthenticatedStockTecidosRoute
  '/encomendas/': typeof AuthenticatedEncomendasIndexRoute
  '/stock/': typeof AuthenticatedStockIndexRoute
  '/encomendas/$id/etiqueta': typeof AuthenticatedEncomendasIdEtiquetaRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/producao': typeof AuthenticatedProducaoRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/admin/catalogo': typeof AuthenticatedAdminCatalogoRoute
  '/admin/colis': typeof AuthenticatedAdminColisRoute
  '/encomendas/nova': typeof AuthenticatedEncomendasNovaRoute
  '/etiquetas/imprimir': typeof AuthenticatedEtiquetasImprimirRoute
  '/producao/cascos': typeof AuthenticatedProducaoCascosRoute
  '/produtos/receitas': typeof AuthenticatedProdutosReceitasRoute
  '/stock/capas': typeof AuthenticatedStockCapasRoute
  '/stock/cascos': typeof AuthenticatedStockCascosRoute
  '/stock/producao': typeof AuthenticatedStockProducaoRoute
  '/stock/tecidos': typeof AuthenticatedStockTecidosRoute
  '/encomendas': typeof AuthenticatedEncomendasIndexRoute
  '/stock': typeof AuthenticatedStockIndexRoute
  '/encomendas/$id/etiqueta': typeof AuthenticatedEncomendasIdEtiquetaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/_authenticated/producao': typeof AuthenticatedProducaoRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/catalogo': typeof AuthenticatedAdminCatalogoRoute
  '/_authenticated/admin/colis': typeof AuthenticatedAdminColisRoute
  '/_authenticated/encomendas/nova': typeof AuthenticatedEncomendasNovaRoute
  '/_authenticated/etiquetas/imprimir': typeof AuthenticatedEtiquetasImprimirRoute
  '/_authenticated/producao/cascos': typeof AuthenticatedProducaoCascosRoute
  '/_authenticated/produtos/receitas': typeof AuthenticatedProdutosReceitasRoute
  '/_authenticated/stock/capas': typeof AuthenticatedStockCapasRoute
  '/_authenticated/stock/cascos': typeof AuthenticatedStockCascosRoute
  '/_authenticated/stock/producao': typeof AuthenticatedStockProducaoRoute
  '/_authenticated/stock/tecidos': typeof AuthenticatedStockTecidosRoute
  '/_authenticated/encomendas/': typeof AuthenticatedEncomendasIndexRoute
  '/_authenticated/stock/': typeof AuthenticatedStockIndexRoute
  '/_authenticated/encomendas/$id/etiqueta': typeof AuthenticatedEncomendasIdEtiquetaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/importar'
    | '/producao'
    | '/admin/catalogo'
    | '/admin/colis'
    | '/encomendas/nova'
    | '/etiquetas/imprimir'
    | '/producao/cascos'
    | '/produtos/receitas'
    | '/stock/capas'
    | '/stock/cascos'
    | '/stock/producao'
    | '/stock/tecidos'
    | '/encomendas/'
    | '/stock/'
    | '/encomendas/$id/etiqueta'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/configuracoes'
    | '/importar'
    | '/producao'
    | '/'
    | '/admin/catalogo'
    | '/admin/colis'
    | '/encomendas/nova'
    | '/etiquetas/imprimir'
    | '/producao/cascos'
    | '/produtos/receitas'
    | '/stock/capas'
    | '/stock/cascos'
    | '/stock/producao'
    | '/stock/tecidos'
    | '/encomendas'
    | '/stock'
    | '/encomendas/$id/etiqueta'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/configuracoes'
    | '/_authenticated/importar'
    | '/_authenticated/producao'
    | '/_authenticated/'
    | '/_authenticated/admin/catalogo'
    | '/_authenticated/admin/colis'
    | '/_authenticated/encomendas/nova'
    | '/_authenticated/etiquetas/imprimir'
    | '/_authenticated/producao/cascos'
    | '/_authenticated/produtos/receitas'
    | '/_authenticated/stock/capas'
    | '/_authenticated/stock/cascos'
    | '/_authenticated/stock/producao'
    | '/_authenticated/stock/tecidos'
    | '/_authenticated/encomendas/'
    | '/_authenticated/stock/'
    | '/_authenticated/encomendas/$id/etiqueta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/producao': {
      id: '/_authenticated/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof AuthenticatedProducaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock/': {
      id: '/_authenticated/stock/'
      path: '/stock'
      fullPath: '/stock/'
      preLoaderRoute: typeof AuthenticatedStockIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/encomendas/': {
      id: '/_authenticated/encomendas/'
      path: '/encomendas'
      fullPath: '/encomendas/'
      preLoaderRoute: typeof AuthenticatedEncomendasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock/tecidos': {
      id: '/_authenticated/stock/tecidos'
      path: '/stock/tecidos'
      fullPath: '/stock/tecidos'
      preLoaderRoute: typeof AuthenticatedStockTecidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock/producao': {
      id: '/_authenticated/stock/producao'
      path: '/stock/producao'
      fullPath: '/stock/producao'
      preLoaderRoute: typeof AuthenticatedStockProducaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock/cascos': {
      id: '/_authenticated/stock/cascos'
      path: '/stock/cascos'
      fullPath: '/stock/cascos'
      preLoaderRoute: typeof AuthenticatedStockCascosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock/capas': {
      id: '/_authenticated/stock/capas'
      path: '/stock/capas'
      fullPath: '/stock/capas'
      preLoaderRoute: typeof AuthenticatedStockCapasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos/receitas': {
      id: '/_authenticated/produtos/receitas'
      path: '/produtos/receitas'
      fullPath: '/produtos/receitas'
      preLoaderRoute: typeof AuthenticatedProdutosReceitasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/producao/cascos': {
      id: '/_authenticated/producao/cascos'
      path: '/cascos'
      fullPath: '/producao/cascos'
      preLoaderRoute: typeof AuthenticatedProducaoCascosRouteImport
      parentRoute: typeof AuthenticatedProducaoRoute
    }
    '/_authenticated/etiquetas/imprimir': {
      id: '/_authenticated/etiquetas/imprimir'
      path: '/etiquetas/imprimir'
      fullPath: '/etiquetas/imprimir'
      preLoaderRoute: typeof AuthenticatedEtiquetasImprimirRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/encomendas/nova': {
      id: '/_authenticated/encomendas/nova'
      path: '/encomendas/nova'
      fullPath: '/encomendas/nova'
      preLoaderRoute: typeof AuthenticatedEncomendasNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/colis': {
      id: '/_authenticated/admin/colis'
      path: '/admin/colis'
      fullPath: '/admin/colis'
      preLoaderRoute: typeof AuthenticatedAdminColisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/catalogo': {
      id: '/_authenticated/admin/catalogo'
      path: '/admin/catalogo'
      fullPath: '/admin/catalogo'
      preLoaderRoute: typeof AuthenticatedAdminCatalogoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/encomendas/$id/etiqueta': {
      id: '/_authenticated/encomendas/$id/etiqueta'
      path: '/encomendas/$id/etiqueta'
      fullPath: '/encomendas/$id/etiqueta'
      preLoaderRoute: typeof AuthenticatedEncomendasIdEtiquetaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedProducaoRouteChildren {
  AuthenticatedProducaoCascosRoute: typeof AuthenticatedProducaoCascosRoute
}

const AuthenticatedProducaoRouteChildren: AuthenticatedProducaoRouteChildren = {
  AuthenticatedProducaoCascosRoute: AuthenticatedProducaoCascosRoute,
}

const AuthenticatedProducaoRouteWithChildren =
  AuthenticatedProducaoRoute._addFileChildren(
    AuthenticatedProducaoRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedProducaoRoute: typeof AuthenticatedProducaoRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminCatalogoRoute: typeof AuthenticatedAdminCatalogoRoute
  AuthenticatedAdminColisRoute: typeof AuthenticatedAdminColisRoute
  AuthenticatedEncomendasNovaRoute: typeof AuthenticatedEncomendasNovaRoute
  AuthenticatedEtiquetasImprimirRoute: typeof AuthenticatedEtiquetasImprimirRoute
  AuthenticatedProdutosReceitasRoute: typeof AuthenticatedProdutosReceitasRoute
  AuthenticatedStockCapasRoute: typeof AuthenticatedStockCapasRoute
  AuthenticatedStockCascosRoute: typeof AuthenticatedStockCascosRoute
  AuthenticatedStockProducaoRoute: typeof AuthenticatedStockProducaoRoute
  AuthenticatedStockTecidosRoute: typeof AuthenticatedStockTecidosRoute
  AuthenticatedEncomendasIndexRoute: typeof AuthenticatedEncomendasIndexRoute
  AuthenticatedStockIndexRoute: typeof AuthenticatedStockIndexRoute
  AuthenticatedEncomendasIdEtiquetaRoute: typeof AuthenticatedEncomendasIdEtiquetaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedProducaoRoute: AuthenticatedProducaoRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminCatalogoRoute: AuthenticatedAdminCatalogoRoute,
  AuthenticatedAdminColisRoute: AuthenticatedAdminColisRoute,
  AuthenticatedEncomendasNovaRoute: AuthenticatedEncomendasNovaRoute,
  AuthenticatedEtiquetasImprimirRoute: AuthenticatedEtiquetasImprimirRoute,
  AuthenticatedProdutosReceitasRoute: AuthenticatedProdutosReceitasRoute,
  AuthenticatedStockCapasRoute: AuthenticatedStockCapasRoute,
  AuthenticatedStockCascosRoute: AuthenticatedStockCascosRoute,
  AuthenticatedStockProducaoRoute: AuthenticatedStockProducaoRoute,
  AuthenticatedStockTecidosRoute: AuthenticatedStockTecidosRoute,
  AuthenticatedEncomendasIndexRoute: AuthenticatedEncomendasIndexRoute,
  AuthenticatedStockIndexRoute: AuthenticatedStockIndexRoute,
  AuthenticatedEncomendasIdEtiquetaRoute:
    AuthenticatedEncomendasIdEtiquetaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
