/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedRetrabalhoRouteImport } from './routes/_authenticated/retrabalho'
import { Route as AuthenticatedPicagemRouteImport } from './routes/_authenticated/picagem'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated/importar'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedStockIndexRouteImport } from './routes/_authenticated/stock.index'
import { Route as AuthenticatedProducaoIndexRouteImport } from './routes/_authenticated/producao.index'
import { Route as AuthenticatedEncomendasIndexRouteImport } from './routes/_authenticated/encomendas.index'
import { Route as AuthenticatedStockTecidosRouteImport } from './routes/_authenticated/stock.tecidos'
import { Route as AuthenticatedStockProdutoFinalRouteImport } from './routes/_authenticated/stock.produto-final'
import { Route as AuthenticatedStockProducaoRouteImport } from './routes/_authenticated/stock.producao'
import { Route as AuthenticatedStockCascosRouteImport } from './routes/_authenticated/stock.cascos'
import { Route as AuthenticatedStockCapasRouteImport } from './routes/_authenticated/stock.capas'
import { Route as AuthenticatedProdutosReceitasRouteImport } from './routes/_authenticated/produtos.receitas'
import { Route as AuthenticatedProducaoCascosRouteImport } from './routes/_authenticated/producao.cascos'
import { Route as AuthenticatedPicagemHistoricoRouteImport } from './routes/_authenticated/picagem.historico'
import { Route as AuthenticatedPicagemConsultaRouteImport } from './routes/_authenticated/picagem.consulta'
import { Route as AuthenticatedEtiquetasImprimirRouteImport } from './routes/_authenticated/etiquetas.imprimir'
import { Route as AuthenticatedEncomendasNovaRouteImport } from './routes/_authenticated/encomendas.nova'
import { Route as AuthenticatedEncomendasImportarSimplesRouteImport } from './routes/_authenticated/encomendas.importar-simples'
import { Route as AuthenticatedAdminSlaRouteImport } from './routes/_authenticated/admin.sla'
import { Route as AuthenticatedAdminRotasColisRouteImport } from './routes/_authenticated/admin.rotas-colis'
import { Route as AuthenticatedAdminRelatoriosRouteImport } from './routes/_authenticated/admin.relatorios'
import { Route as AuthenticatedAdminQualidadeRouteImport } from './routes/_authenticated/admin.qualidade'
import { Route as AuthenticatedAdminPlaneamentoRouteImport } from './routes/_authenticated/admin.planeamento'
import { Route as AuthenticatedAdminColisRouteImport } from './routes/_authenticated/admin.colis'
import { Route as AuthenticatedAdminCatalogoRouteImport } from './routes/_authenticated/admin.catalogo'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedEncomendasIdEtiquetaRouteImport } from './routes/_authenticated/encomendas.$id.etiqueta'
import { Route as AuthenticatedAdminPlaneamentoCargaRouteImport } from './routes/_authenticated/admin.planeamento.carga'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRetrabalhoRoute = AuthenticatedRetrabalhoRouteImport.update({
  id: '/retrabalho',
  path: '/retrabalho',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPicagemRoute = AuthenticatedPicagemRouteImport.update({
  id: '/picagem',
  path: '/picagem',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedStockIndexRoute = AuthenticatedStockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProducaoIndexRoute =
  AuthenticatedProducaoIndexRouteImport.update({
    id: '/producao/',
    path: '/producao/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEncomendasIndexRoute =
  AuthenticatedEncomendasIndexRouteImport.update({
    id: '/encomendas/',
    path: '/encomendas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockTecidosRoute =
  AuthenticatedStockTecidosRouteImport.update({
    id: '/stock/tecidos',
    path: '/stock/tecidos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockProdutoFinalRoute =
  AuthenticatedStockProdutoFinalRouteImport.update({
    id: '/stock/produto-final',
    path: '/stock/produto-final',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockProducaoRoute =
  AuthenticatedStockProducaoRouteImport.update({
    id: '/stock/producao',
    path: '/stock/producao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockCascosRoute =
  AuthenticatedStockCascosRouteImport.update({
    id: '/stock/cascos',
    path: '/stock/cascos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockCapasRoute = AuthenticatedStockCapasRouteImport.update({
  id: '/stock/capas',
  path: '/stock/capas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosReceitasRoute =
  AuthenticatedProdutosReceitasRouteImport.update({
    id: '/produtos/receitas',
    path: '/produtos/receitas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProducaoCascosRoute =
  AuthenticatedProducaoCascosRouteImport.update({
    id: '/producao/cascos',
    path: '/producao/cascos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPicagemHistoricoRoute =
  AuthenticatedPicagemHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedPicagemRoute,
  } as any)
const AuthenticatedPicagemConsultaRoute =
  AuthenticatedPicagemConsultaRouteImport.update({
    id: '/consulta',
    path: '/consulta',
    getParentRoute: () => AuthenticatedPicagemRoute,
  } as any)
const AuthenticatedEtiquetasImprimirRoute =
  AuthenticatedEtiquetasImprimirRouteImport.update({
    id: '/etiquetas/imprimir',
    path: '/etiquetas/imprimir',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEncomendasNovaRoute =
  AuthenticatedEncomendasNovaRouteImport.update({
    id: '/encomendas/nova',
    path: '/encomendas/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEncomendasImportarSimplesRoute =
  AuthenticatedEncomendasImportarSimplesRouteImport.update({
    id: '/encomendas/importar-simples',
    path: '/encomendas/importar-simples',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSlaRoute = AuthenticatedAdminSlaRouteImport.update({
  id: '/admin/sla',
  path: '/admin/sla',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRotasColisRoute =
  AuthenticatedAdminRotasColisRouteImport.update({
    id: '/admin/rotas-colis',
    path: '/admin/rotas-colis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRelatoriosRoute =
  AuthenticatedAdminRelatoriosRouteImport.update({
    id: '/admin/relatorios',
    path: '/admin/relatorios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminQualidadeRoute =
  AuthenticatedAdminQualidadeRouteImport.update({
    id: '/admin/qualidade',
    path: '/admin/qualidade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPlaneamentoRoute =
  AuthenticatedAdminPlaneamentoRouteImport.update({
    id: '/admin/planeamento',
    path: '/admin/planeamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminColisRoute = AuthenticatedAdminColisRouteImport.update({
  id: '/admin/colis',
  path: '/admin/colis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCatalogoRoute =
  AuthenticatedAdminCatalogoRouteImport.update({
    id: '/admin/catalogo',
    path: '/admin/catalogo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedEncomendasIdEtiquetaRoute =
  AuthenticatedEncomendasIdEtiquetaRouteImport.update({
    id: '/encomendas/$id/etiqueta',
    path: '/encomendas/$id/etiqueta',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPlaneamentoCargaRoute =
  AuthenticatedAdminPlaneamentoCargaRouteImport.update({
    id: '/carga',
    path: '/carga',
    getParentRoute: () => AuthenticatedAdminPlaneamentoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/picagem': typeof AuthenticatedPicagemRouteWithChildren
  '/retrabalho': typeof AuthenticatedRetrabalhoRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/catalogo': typeof AuthenticatedAdminCatalogoRoute
  '/admin/colis': typeof AuthenticatedAdminColisRoute
  '/admin/planeamento': typeof AuthenticatedAdminPlaneamentoRouteWithChildren
  '/admin/qualidade': typeof AuthenticatedAdminQualidadeRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/rotas-colis': typeof AuthenticatedAdminRotasColisRoute
  '/admin/sla': typeof AuthenticatedAdminSlaRoute
  '/encomendas/importar-simples': typeof AuthenticatedEncomendasImportarSimplesRoute
  '/encomendas/nova': typeof AuthenticatedEncomendasNovaRoute
  '/etiquetas/imprimir': typeof AuthenticatedEtiquetasImprimirRoute
  '/picagem/consulta': typeof AuthenticatedPicagemConsultaRoute
  '/picagem/historico': typeof AuthenticatedPicagemHistoricoRoute
  '/producao/cascos': typeof AuthenticatedProducaoCascosRoute
  '/produtos/receitas': typeof AuthenticatedProdutosReceitasRoute
  '/stock/capas': typeof AuthenticatedStockCapasRoute
  '/stock/cascos': typeof AuthenticatedStockCascosRoute
  '/stock/producao': typeof AuthenticatedStockProducaoRoute
  '/stock/produto-final': typeof AuthenticatedStockProdutoFinalRoute
  '/stock/tecidos': typeof AuthenticatedStockTecidosRoute
  '/encomendas/': typeof AuthenticatedEncomendasIndexRoute
  '/producao/': typeof AuthenticatedProducaoIndexRoute
  '/stock/': typeof AuthenticatedStockIndexRoute
  '/admin/planeamento/carga': typeof AuthenticatedAdminPlaneamentoCargaRoute
  '/encomendas/$id/etiqueta': typeof AuthenticatedEncomendasIdEtiquetaRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/picagem': typeof AuthenticatedPicagemRouteWithChildren
  '/retrabalho': typeof AuthenticatedRetrabalhoRoute
  '/': typeof AuthenticatedIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/catalogo': typeof AuthenticatedAdminCatalogoRoute
  '/admin/colis': typeof AuthenticatedAdminColisRoute
  '/admin/planeamento': typeof AuthenticatedAdminPlaneamentoRouteWithChildren
  '/admin/qualidade': typeof AuthenticatedAdminQualidadeRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/rotas-colis': typeof AuthenticatedAdminRotasColisRoute
  '/admin/sla': typeof AuthenticatedAdminSlaRoute
  '/encomendas/importar-simples': typeof AuthenticatedEncomendasImportarSimplesRoute
  '/encomendas/nova': typeof AuthenticatedEncomendasNovaRoute
  '/etiquetas/imprimir': typeof AuthenticatedEtiquetasImprimirRoute
  '/picagem/consulta': typeof AuthenticatedPicagemConsultaRoute
  '/picagem/historico': typeof AuthenticatedPicagemHistoricoRoute
  '/producao/cascos': typeof AuthenticatedProducaoCascosRoute
  '/produtos/receitas': typeof AuthenticatedProdutosReceitasRoute
  '/stock/capas': typeof AuthenticatedStockCapasRoute
  '/stock/cascos': typeof AuthenticatedStockCascosRoute
  '/stock/producao': typeof AuthenticatedStockProducaoRoute
  '/stock/produto-final': typeof AuthenticatedStockProdutoFinalRoute
  '/stock/tecidos': typeof AuthenticatedStockTecidosRoute
  '/encomendas': typeof AuthenticatedEncomendasIndexRoute
  '/producao': typeof AuthenticatedProducaoIndexRoute
  '/stock': typeof AuthenticatedStockIndexRoute
  '/admin/planeamento/carga': typeof AuthenticatedAdminPlaneamentoCargaRoute
  '/encomendas/$id/etiqueta': typeof AuthenticatedEncomendasIdEtiquetaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/_authenticated/picagem': typeof AuthenticatedPicagemRouteWithChildren
  '/_authenticated/retrabalho': typeof AuthenticatedRetrabalhoRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/catalogo': typeof AuthenticatedAdminCatalogoRoute
  '/_authenticated/admin/colis': typeof AuthenticatedAdminColisRoute
  '/_authenticated/admin/planeamento': typeof AuthenticatedAdminPlaneamentoRouteWithChildren
  '/_authenticated/admin/qualidade': typeof AuthenticatedAdminQualidadeRoute
  '/_authenticated/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/_authenticated/admin/rotas-colis': typeof AuthenticatedAdminRotasColisRoute
  '/_authenticated/admin/sla': typeof AuthenticatedAdminSlaRoute
  '/_authenticated/encomendas/importar-simples': typeof AuthenticatedEncomendasImportarSimplesRoute
  '/_authenticated/encomendas/nova': typeof AuthenticatedEncomendasNovaRoute
  '/_authenticated/etiquetas/imprimir': typeof AuthenticatedEtiquetasImprimirRoute
  '/_authenticated/picagem/consulta': typeof AuthenticatedPicagemConsultaRoute
  '/_authenticated/picagem/historico': typeof AuthenticatedPicagemHistoricoRoute
  '/_authenticated/producao/cascos': typeof AuthenticatedProducaoCascosRoute
  '/_authenticated/produtos/receitas': typeof AuthenticatedProdutosReceitasRoute
  '/_authenticated/stock/capas': typeof AuthenticatedStockCapasRoute
  '/_authenticated/stock/cascos': typeof AuthenticatedStockCascosRoute
  '/_authenticated/stock/producao': typeof AuthenticatedStockProducaoRoute
  '/_authenticated/stock/produto-final': typeof AuthenticatedStockProdutoFinalRoute
  '/_authenticated/stock/tecidos': typeof AuthenticatedStockTecidosRoute
  '/_authenticated/encomendas/': typeof AuthenticatedEncomendasIndexRoute
  '/_authenticated/producao/': typeof AuthenticatedProducaoIndexRoute
  '/_authenticated/stock/': typeof AuthenticatedStockIndexRoute
  '/_authenticated/admin/planeamento/carga': typeof AuthenticatedAdminPlaneamentoCargaRoute
  '/_authenticated/encomendas/$id/etiqueta': typeof AuthenticatedEncomendasIdEtiquetaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/configuracoes'
    | '/importar'
    | '/picagem'
    | '/retrabalho'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/catalogo'
    | '/admin/colis'
    | '/admin/planeamento'
    | '/admin/qualidade'
    | '/admin/relatorios'
    | '/admin/rotas-colis'
    | '/admin/sla'
    | '/encomendas/importar-simples'
    | '/encomendas/nova'
    | '/etiquetas/imprimir'
    | '/picagem/consulta'
    | '/picagem/historico'
    | '/producao/cascos'
    | '/produtos/receitas'
    | '/stock/capas'
    | '/stock/cascos'
    | '/stock/producao'
    | '/stock/produto-final'
    | '/stock/tecidos'
    | '/encomendas/'
    | '/producao/'
    | '/stock/'
    | '/admin/planeamento/carga'
    | '/encomendas/$id/etiqueta'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/configuracoes'
    | '/importar'
    | '/picagem'
    | '/retrabalho'
    | '/'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/catalogo'
    | '/admin/colis'
    | '/admin/planeamento'
    | '/admin/qualidade'
    | '/admin/relatorios'
    | '/admin/rotas-colis'
    | '/admin/sla'
    | '/encomendas/importar-simples'
    | '/encomendas/nova'
    | '/etiquetas/imprimir'
    | '/picagem/consulta'
    | '/picagem/historico'
    | '/producao/cascos'
    | '/produtos/receitas'
    | '/stock/capas'
    | '/stock/cascos'
    | '/stock/producao'
    | '/stock/produto-final'
    | '/stock/tecidos'
    | '/encomendas'
    | '/producao'
    | '/stock'
    | '/admin/planeamento/carga'
    | '/encomendas/$id/etiqueta'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/configuracoes'
    | '/_authenticated/importar'
    | '/_authenticated/picagem'
    | '/_authenticated/retrabalho'
    | '/_authenticated/'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/catalogo'
    | '/_authenticated/admin/colis'
    | '/_authenticated/admin/planeamento'
    | '/_authenticated/admin/qualidade'
    | '/_authenticated/admin/relatorios'
    | '/_authenticated/admin/rotas-colis'
    | '/_authenticated/admin/sla'
    | '/_authenticated/encomendas/importar-simples'
    | '/_authenticated/encomendas/nova'
    | '/_authenticated/etiquetas/imprimir'
    | '/_authenticated/picagem/consulta'
    | '/_authenticated/picagem/historico'
    | '/_authenticated/producao/cascos'
    | '/_authenticated/produtos/receitas'
    | '/_authenticated/stock/capas'
    | '/_authenticated/stock/cascos'
    | '/_authenticated/stock/producao'
    | '/_authenticated/stock/produto-final'
    | '/_authenticated/stock/tecidos'
    | '/_authenticated/encomendas/'
    | '/_authenticated/producao/'
    | '/_authenticated/stock/'
    | '/_authenticated/admin/planeamento/carga'
    | '/_authenticated/encomendas/$id/etiqueta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/retrabalho': {
      id: '/_authenticated/retrabalho'
      path: '/retrabalho'
      fullPath: '/retrabalho'
      preLoaderRoute: typeof AuthenticatedRetrabalhoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/picagem': {
      id: '/_authenticated/picagem'
      path: '/picagem'
      fullPath: '/picagem'
      preLoaderRoute: typeof AuthenticatedPicagemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stock/': {
      id: '/_authenticated/stock/'
      path: '/stock'
      fullPath: '/stock/'
      preLoaderRoute: typeof AuthenticatedStockIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/producao/': {
      id: '/_authenticated/producao/'
      path: '/producao'
      fullPath: '/producao/'
      preLoaderRoute: typeof AuthenticatedProducaoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/encomendas/': {
      id: '/_authenticated/encomendas/'
      path: '/encomendas'
      fullPath: '/encomendas/'
      preLoaderRoute: typeof AuthenticatedEncomendasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock/tecidos': {
      id: '/_authenticated/stock/tecidos'
      path: '/stock/tecidos'
      fullPath: '/stock/tecidos'
      preLoaderRoute: typeof AuthenticatedStockTecidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock/produto-final': {
      id: '/_authenticated/stock/produto-final'
      path: '/stock/produto-final'
      fullPath: '/stock/produto-final'
      preLoaderRoute: typeof AuthenticatedStockProdutoFinalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock/producao': {
      id: '/_authenticated/stock/producao'
      path: '/stock/producao'
      fullPath: '/stock/producao'
      preLoaderRoute: typeof AuthenticatedStockProducaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock/cascos': {
      id: '/_authenticated/stock/cascos'
      path: '/stock/cascos'
      fullPath: '/stock/cascos'
      preLoaderRoute: typeof AuthenticatedStockCascosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock/capas': {
      id: '/_authenticated/stock/capas'
      path: '/stock/capas'
      fullPath: '/stock/capas'
      preLoaderRoute: typeof AuthenticatedStockCapasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos/receitas': {
      id: '/_authenticated/produtos/receitas'
      path: '/produtos/receitas'
      fullPath: '/produtos/receitas'
      preLoaderRoute: typeof AuthenticatedProdutosReceitasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/producao/cascos': {
      id: '/_authenticated/producao/cascos'
      path: '/producao/cascos'
      fullPath: '/producao/cascos'
      preLoaderRoute: typeof AuthenticatedProducaoCascosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/picagem/historico': {
      id: '/_authenticated/picagem/historico'
      path: '/historico'
      fullPath: '/picagem/historico'
      preLoaderRoute: typeof AuthenticatedPicagemHistoricoRouteImport
      parentRoute: typeof AuthenticatedPicagemRoute
    }
    '/_authenticated/picagem/consulta': {
      id: '/_authenticated/picagem/consulta'
      path: '/consulta'
      fullPath: '/picagem/consulta'
      preLoaderRoute: typeof AuthenticatedPicagemConsultaRouteImport
      parentRoute: typeof AuthenticatedPicagemRoute
    }
    '/_authenticated/etiquetas/imprimir': {
      id: '/_authenticated/etiquetas/imprimir'
      path: '/etiquetas/imprimir'
      fullPath: '/etiquetas/imprimir'
      preLoaderRoute: typeof AuthenticatedEtiquetasImprimirRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/encomendas/nova': {
      id: '/_authenticated/encomendas/nova'
      path: '/encomendas/nova'
      fullPath: '/encomendas/nova'
      preLoaderRoute: typeof AuthenticatedEncomendasNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/encomendas/importar-simples': {
      id: '/_authenticated/encomendas/importar-simples'
      path: '/encomendas/importar-simples'
      fullPath: '/encomendas/importar-simples'
      preLoaderRoute: typeof AuthenticatedEncomendasImportarSimplesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/sla': {
      id: '/_authenticated/admin/sla'
      path: '/admin/sla'
      fullPath: '/admin/sla'
      preLoaderRoute: typeof AuthenticatedAdminSlaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/rotas-colis': {
      id: '/_authenticated/admin/rotas-colis'
      path: '/admin/rotas-colis'
      fullPath: '/admin/rotas-colis'
      preLoaderRoute: typeof AuthenticatedAdminRotasColisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/relatorios': {
      id: '/_authenticated/admin/relatorios'
      path: '/admin/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AuthenticatedAdminRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/qualidade': {
      id: '/_authenticated/admin/qualidade'
      path: '/admin/qualidade'
      fullPath: '/admin/qualidade'
      preLoaderRoute: typeof AuthenticatedAdminQualidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/planeamento': {
      id: '/_authenticated/admin/planeamento'
      path: '/admin/planeamento'
      fullPath: '/admin/planeamento'
      preLoaderRoute: typeof AuthenticatedAdminPlaneamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/colis': {
      id: '/_authenticated/admin/colis'
      path: '/admin/colis'
      fullPath: '/admin/colis'
      preLoaderRoute: typeof AuthenticatedAdminColisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/catalogo': {
      id: '/_authenticated/admin/catalogo'
      path: '/admin/catalogo'
      fullPath: '/admin/catalogo'
      preLoaderRoute: typeof AuthenticatedAdminCatalogoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/encomendas/$id/etiqueta': {
      id: '/_authenticated/encomendas/$id/etiqueta'
      path: '/encomendas/$id/etiqueta'
      fullPath: '/encomendas/$id/etiqueta'
      preLoaderRoute: typeof AuthenticatedEncomendasIdEtiquetaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/planeamento/carga': {
      id: '/_authenticated/admin/planeamento/carga'
      path: '/carga'
      fullPath: '/admin/planeamento/carga'
      preLoaderRoute: typeof AuthenticatedAdminPlaneamentoCargaRouteImport
      parentRoute: typeof AuthenticatedAdminPlaneamentoRoute
    }
  }
}

interface AuthenticatedPicagemRouteChildren {
  AuthenticatedPicagemConsultaRoute: typeof AuthenticatedPicagemConsultaRoute
  AuthenticatedPicagemHistoricoRoute: typeof AuthenticatedPicagemHistoricoRoute
}

const AuthenticatedPicagemRouteChildren: AuthenticatedPicagemRouteChildren = {
  AuthenticatedPicagemConsultaRoute: AuthenticatedPicagemConsultaRoute,
  AuthenticatedPicagemHistoricoRoute: AuthenticatedPicagemHistoricoRoute,
}

const AuthenticatedPicagemRouteWithChildren =
  AuthenticatedPicagemRoute._addFileChildren(AuthenticatedPicagemRouteChildren)

interface AuthenticatedAdminPlaneamentoRouteChildren {
  AuthenticatedAdminPlaneamentoCargaRoute: typeof AuthenticatedAdminPlaneamentoCargaRoute
}

const AuthenticatedAdminPlaneamentoRouteChildren: AuthenticatedAdminPlaneamentoRouteChildren =
  {
    AuthenticatedAdminPlaneamentoCargaRoute:
      AuthenticatedAdminPlaneamentoCargaRoute,
  }

const AuthenticatedAdminPlaneamentoRouteWithChildren =
  AuthenticatedAdminPlaneamentoRoute._addFileChildren(
    AuthenticatedAdminPlaneamentoRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedPicagemRoute: typeof AuthenticatedPicagemRouteWithChildren
  AuthenticatedRetrabalhoRoute: typeof AuthenticatedRetrabalhoRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminCatalogoRoute: typeof AuthenticatedAdminCatalogoRoute
  AuthenticatedAdminColisRoute: typeof AuthenticatedAdminColisRoute
  AuthenticatedAdminPlaneamentoRoute: typeof AuthenticatedAdminPlaneamentoRouteWithChildren
  AuthenticatedAdminQualidadeRoute: typeof AuthenticatedAdminQualidadeRoute
  AuthenticatedAdminRelatoriosRoute: typeof AuthenticatedAdminRelatoriosRoute
  AuthenticatedAdminRotasColisRoute: typeof AuthenticatedAdminRotasColisRoute
  AuthenticatedAdminSlaRoute: typeof AuthenticatedAdminSlaRoute
  AuthenticatedEncomendasImportarSimplesRoute: typeof AuthenticatedEncomendasImportarSimplesRoute
  AuthenticatedEncomendasNovaRoute: typeof AuthenticatedEncomendasNovaRoute
  AuthenticatedEtiquetasImprimirRoute: typeof AuthenticatedEtiquetasImprimirRoute
  AuthenticatedProducaoCascosRoute: typeof AuthenticatedProducaoCascosRoute
  AuthenticatedProdutosReceitasRoute: typeof AuthenticatedProdutosReceitasRoute
  AuthenticatedStockCapasRoute: typeof AuthenticatedStockCapasRoute
  AuthenticatedStockCascosRoute: typeof AuthenticatedStockCascosRoute
  AuthenticatedStockProducaoRoute: typeof AuthenticatedStockProducaoRoute
  AuthenticatedStockProdutoFinalRoute: typeof AuthenticatedStockProdutoFinalRoute
  AuthenticatedStockTecidosRoute: typeof AuthenticatedStockTecidosRoute
  AuthenticatedEncomendasIndexRoute: typeof AuthenticatedEncomendasIndexRoute
  AuthenticatedProducaoIndexRoute: typeof AuthenticatedProducaoIndexRoute
  AuthenticatedStockIndexRoute: typeof AuthenticatedStockIndexRoute
  AuthenticatedEncomendasIdEtiquetaRoute: typeof AuthenticatedEncomendasIdEtiquetaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedPicagemRoute: AuthenticatedPicagemRouteWithChildren,
  AuthenticatedRetrabalhoRoute: AuthenticatedRetrabalhoRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminCatalogoRoute: AuthenticatedAdminCatalogoRoute,
  AuthenticatedAdminColisRoute: AuthenticatedAdminColisRoute,
  AuthenticatedAdminPlaneamentoRoute:
    AuthenticatedAdminPlaneamentoRouteWithChildren,
  AuthenticatedAdminQualidadeRoute: AuthenticatedAdminQualidadeRoute,
  AuthenticatedAdminRelatoriosRoute: AuthenticatedAdminRelatoriosRoute,
  AuthenticatedAdminRotasColisRoute: AuthenticatedAdminRotasColisRoute,
  AuthenticatedAdminSlaRoute: AuthenticatedAdminSlaRoute,
  AuthenticatedEncomendasImportarSimplesRoute:
    AuthenticatedEncomendasImportarSimplesRoute,
  AuthenticatedEncomendasNovaRoute: AuthenticatedEncomendasNovaRoute,
  AuthenticatedEtiquetasImprimirRoute: AuthenticatedEtiquetasImprimirRoute,
  AuthenticatedProducaoCascosRoute: AuthenticatedProducaoCascosRoute,
  AuthenticatedProdutosReceitasRoute: AuthenticatedProdutosReceitasRoute,
  AuthenticatedStockCapasRoute: AuthenticatedStockCapasRoute,
  AuthenticatedStockCascosRoute: AuthenticatedStockCascosRoute,
  AuthenticatedStockProducaoRoute: AuthenticatedStockProducaoRoute,
  AuthenticatedStockProdutoFinalRoute: AuthenticatedStockProdutoFinalRoute,
  AuthenticatedStockTecidosRoute: AuthenticatedStockTecidosRoute,
  AuthenticatedEncomendasIndexRoute: AuthenticatedEncomendasIndexRoute,
  AuthenticatedProducaoIndexRoute: AuthenticatedProducaoIndexRoute,
  AuthenticatedStockIndexRoute: AuthenticatedStockIndexRoute,
  AuthenticatedEncomendasIdEtiquetaRoute:
    AuthenticatedEncomendasIdEtiquetaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
